Repository playcanvas/pcui-graph, pull requests merged in 2021-11, with the labels that each got.

#16 Updating install instructions to what a developer most likely needs to run
  README.md
Labels: documentation

#18 Graph updates for version control
  .storybook/stories/advanced/version-control.stories.jsx
  package-lock.json
  package.json
  rollup.config.js
  src/constants.js
  src/graph-view-edge.js
  src/graph-view-node.js
  src/graph-view.js
  src/index.js
  src/joint-graph.js
  src/joint-shape-node.js
  src/style.scss
Labels: enhancement

#19 Node attributes update
  .storybook/stories/basic/node-attributes.jsx
  src/graph-view-node.js
  src/index.js
Labels: enhancement

#20 Node attribute input creation fix
  src/graph-view-node.js
Labels: bug
